spring:
  config:
    import: classpath:custom.yml
  datasource:
    url: jdbc:mysql://localhost:3306/gradle_demo?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2b8&rewriteBatchedStatements=true
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    open-in-view: true
    properties:
      jakarta:
        persistence:
          sharedCache:
            mode: UNSPECIFIED
      hibernate:
        format_sql: true
    show-sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
server:
  error:
    include-message: always
    include-binding-errors: always
    # only if we include the trace param in the URL (?trace=true), we'll get a stack trace in the response payload.
    include-stacktrace: on_param
    include-exception: false